// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data;

#nullable disable

namespace Restaurant.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    partial class RestauranteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Itens");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "O saboroso e mais aclamado da casa!",
                            Name = "X-Burguer",
                            Price = 20.899999999999999
                        },
                        new
                        {
                            Id = 2,
                            Description = "O preferido",
                            Name = "X-House",
                            Price = 30.899999999999999
                        },
                        new
                        {
                            Id = 3,
                            Description = "O delicioso e mais pedido",
                            Name = "Strogonoff",
                            Price = 22.899999999999999
                        },
                        new
                        {
                            Id = 4,
                            Description = "O sabor especial e secreto do chefe",
                            Name = "Secret",
                            Price = 24.899999999999999
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
