// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Restaurant.Data;

#nullable disable

namespace Restaurant.Migrations
{
    [DbContext(typeof(RestauranteDbContext))]
    partial class RestauranteDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Restaurant.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ItemId");

                    b.ToTable("Itens");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            Description = "O saboroso e mais aclamado da casa!",
                            Name = "X-Burguer",
                            Price = 20.899999999999999
                        },
                        new
                        {
                            ItemId = 2,
                            Description = "O preferido",
                            Name = "X-House",
                            Price = 30.899999999999999
                        },
                        new
                        {
                            ItemId = 3,
                            Description = "O delicioso e mais pedido",
                            Name = "Strogonoff",
                            Price = 22.899999999999999
                        },
                        new
                        {
                            ItemId = 4,
                            Description = "O sabor especial e secreto do chefe",
                            Name = "Secret",
                            Price = 24.899999999999999
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Mesa", b =>
                {
                    b.Property<int>("MesaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MesaId"));

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.HasKey("MesaId");

                    b.HasIndex("StatusId");

                    b.ToTable("mesas");

                    b.HasData(
                        new
                        {
                            MesaId = 1,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 2,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 3,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 4,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 5,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 6,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 7,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 8,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 9,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 10,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 11,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 12,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 13,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 14,
                            StatusId = 1
                        },
                        new
                        {
                            MesaId = 15,
                            StatusId = 1
                        });
                });

            modelBuilder.Entity("Restaurant.Models.MesaItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("MesaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("MesaId");

                    b.ToTable("mesasitens");
                });

            modelBuilder.Entity("Restaurant.Models.Status", b =>
                {
                    b.Property<int>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StatusId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StatusId");

                    b.ToTable("Status");

                    b.HasData(
                        new
                        {
                            StatusId = 1,
                            Name = "Aberta"
                        },
                        new
                        {
                            StatusId = 2,
                            Name = "Fechada"
                        });
                });

            modelBuilder.Entity("Restaurant.Models.Mesa", b =>
                {
                    b.HasOne("Restaurant.Models.Status", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Restaurant.Models.MesaItem", b =>
                {
                    b.HasOne("Restaurant.Models.Item", "item")
                        .WithMany("MesaItens")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Restaurant.Models.Mesa", "mesa")
                        .WithMany("MesaItens")
                        .HasForeignKey("MesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");

                    b.Navigation("mesa");
                });

            modelBuilder.Entity("Restaurant.Models.Item", b =>
                {
                    b.Navigation("MesaItens");
                });

            modelBuilder.Entity("Restaurant.Models.Mesa", b =>
                {
                    b.Navigation("MesaItens");
                });
#pragma warning restore 612, 618
        }
    }
}
